language: python
python:
 - 2.7
 - 3.5

before_install:
 - pip install -r requirements.txt
 - python setup.py install
 - python bootstrap.py
 - ./bin/buildout

script:
 - nosetests -i regulartest -i sphinxtest
 
