name: Python package

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.10', '3.11', '3.12', '3.13', '3.14']
        experimental: [false]
        # include:
        #   - python-version: '3.14-rc'
        #     experimental: true

    steps:
    - uses: actions/checkout@v5
    - name: Install uv
      uses: astral-sh/setup-uv@v6
      with:
        enable-cache: true
    - name: Set up Python ${{ matrix.python-version }}
      run: uv python install ${{ matrix.python-version }}
    - name: Install apt dependencies
      run: |
        sudo apt-get update && sudo apt-get -y install plantuml libxml2-dev libxslt-dev python3-dev libffi-dev libcairo2-dev pkg-config
    - name: Install dependencies for Python
      run: |
        uv sync --all-extras --python ${{ matrix.python-version }}
      env:
        PYO3_USE_ABI3_FORWARD_COMPATIBILITY: 1
    - name: Lint
      run: |
        uvx pre-commit run --all-files --show-diff-on-failure
      if: matrix.python-version == '3.12'
    - name: Test with pytest
      run: |
        uv run pytest -v
    - name: Archive test output
      uses: actions/upload-artifact@v5
      if: failure()
      with:
        name: failed-tests-${{ matrix.python-version }}
        path: tests/output
        retention-days: 8
