name: Python package

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      matrix:
        python-version: ['3.8', '3.9', '3.10']
        experimental: [false]
        include:
          - python-version: '3.11'
            experimental: true

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install apt dependencies
      run: |
        sudo apt-get update && sudo apt-get -y install plantuml libxml2-dev libxslt-dev python3-dev
    - name: Install pip & test dependencies
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade setuptools
        pip install pytest pre-commit
    - name: Install dependencies for Python
      run: |
        pip install -c requirements.txt -e .[tests,sphinx,svgsupport,aafiguresupport,mathsupport,rawhtmlsupport]
    - name: Lint
      run: |
        pre-commit run --all-files --show-diff-on-failure
      if: matrix.python-version == '3.8'
    - name: Test with pytest
      continue-on-error: true
      run: |
        pytest -v
    - name: Archive test output
      uses: actions/upload-artifact@v2
      if: failure()
      with:
        name: failed-tests
        path: tests/output
        retention-days: 8
