name: Python package

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      matrix:
        python-version: ['3.9', '3.10', '3.11', '3.12', '3.13']
        experimental: [false]
        # include:
        #   - python-version: '3.14-rc'
        #     experimental: true

    steps:
    - uses: actions/checkout@v4
    - name: Install uv
      uses: astral-sh/setup-uv@v5
      with:
        enable-cache: true
        # Install a specific version of uv.
        version: "0.4.x"
    - name: Set up Python ${{ matrix.python-version }}
      run: uv python install ${{ matrix.python-version }}
    - name: Install apt dependencies
      run: |
        sudo apt-get update && sudo apt-get -y install plantuml libxml2-dev libxslt-dev python3-dev
    - name: Install dependencies for Python
      run: |
        uv sync --all-extras --python ${{ matrix.python-version }}
    - name: Lint
      run: |
        uvx pre-commit run --all-files --show-diff-on-failure
      if: matrix.python-version == '3.12'
    - name: Test with pytest
      run: |
        uv run pytest -v
    - name: Archive test output
      uses: actions/upload-artifact@v4
      if: failure()
      with:
        name: failed-tests
        path: tests/output
        retention-days: 8
